spring:
  application:
    name: authentication-server
  security:
    user:
      name: "user"
      password: "pass"
    oauth2:
      authorization-server:
        client:
          main-client:
            registration:
              client-id: "main-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              scopes:
                - "openid"
                - "profile"
              redirect-uris:
                - "https://oauth.pstmn.io/v1/callback"
logging.level.org.springframework.security: DEBUG